apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: functionservices.yijun.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: yijun.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      # A schema is required
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                functionName:
                  type: string
                replicas:
                  type: integer
            status:
              type: string
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: functionservices
    # singular name to be used as an alias on the CLI and for display
    singular: functionservice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: FunctionService
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - fs
